/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedManajemenPenggunaRouteImport } from './routes/_authenticated/manajemen-pengguna'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBarangMasukRouteImport } from './routes/_authenticated/barang-masuk'
import { Route as AuthenticatedBarangKeluarRouteImport } from './routes/_authenticated/barang-keluar'
import { Route as AuthenticatedBarangRouteImport } from './routes/_authenticated/barang'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManajemenPenggunaRoute =
  AuthenticatedManajemenPenggunaRouteImport.update({
    id: '/manajemen-pengguna',
    path: '/manajemen-pengguna',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBarangMasukRoute =
  AuthenticatedBarangMasukRouteImport.update({
    id: '/barang-masuk',
    path: '/barang-masuk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBarangKeluarRoute =
  AuthenticatedBarangKeluarRouteImport.update({
    id: '/barang-keluar',
    path: '/barang-keluar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBarangRoute = AuthenticatedBarangRouteImport.update({
  id: '/barang',
  path: '/barang',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/barang': typeof AuthenticatedBarangRoute
  '/barang-keluar': typeof AuthenticatedBarangKeluarRoute
  '/barang-masuk': typeof AuthenticatedBarangMasukRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/manajemen-pengguna': typeof AuthenticatedManajemenPenggunaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/barang': typeof AuthenticatedBarangRoute
  '/barang-keluar': typeof AuthenticatedBarangKeluarRoute
  '/barang-masuk': typeof AuthenticatedBarangMasukRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/manajemen-pengguna': typeof AuthenticatedManajemenPenggunaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/barang': typeof AuthenticatedBarangRoute
  '/_authenticated/barang-keluar': typeof AuthenticatedBarangKeluarRoute
  '/_authenticated/barang-masuk': typeof AuthenticatedBarangMasukRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/manajemen-pengguna': typeof AuthenticatedManajemenPenggunaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/barang'
    | '/barang-keluar'
    | '/barang-masuk'
    | '/dashboard'
    | '/manajemen-pengguna'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/barang'
    | '/barang-keluar'
    | '/barang-masuk'
    | '/dashboard'
    | '/manajemen-pengguna'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/barang'
    | '/_authenticated/barang-keluar'
    | '/_authenticated/barang-masuk'
    | '/_authenticated/dashboard'
    | '/_authenticated/manajemen-pengguna'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manajemen-pengguna': {
      id: '/_authenticated/manajemen-pengguna'
      path: '/manajemen-pengguna'
      fullPath: '/manajemen-pengguna'
      preLoaderRoute: typeof AuthenticatedManajemenPenggunaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barang-masuk': {
      id: '/_authenticated/barang-masuk'
      path: '/barang-masuk'
      fullPath: '/barang-masuk'
      preLoaderRoute: typeof AuthenticatedBarangMasukRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barang-keluar': {
      id: '/_authenticated/barang-keluar'
      path: '/barang-keluar'
      fullPath: '/barang-keluar'
      preLoaderRoute: typeof AuthenticatedBarangKeluarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barang': {
      id: '/_authenticated/barang'
      path: '/barang'
      fullPath: '/barang'
      preLoaderRoute: typeof AuthenticatedBarangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBarangRoute: typeof AuthenticatedBarangRoute
  AuthenticatedBarangKeluarRoute: typeof AuthenticatedBarangKeluarRoute
  AuthenticatedBarangMasukRoute: typeof AuthenticatedBarangMasukRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedManajemenPenggunaRoute: typeof AuthenticatedManajemenPenggunaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBarangRoute: AuthenticatedBarangRoute,
  AuthenticatedBarangKeluarRoute: AuthenticatedBarangKeluarRoute,
  AuthenticatedBarangMasukRoute: AuthenticatedBarangMasukRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedManajemenPenggunaRoute: AuthenticatedManajemenPenggunaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
